<?php

namespace DiaporamaBundle\Repository;
use Doctrine\ORM\Query\Expr;

/**
 * GalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllGaleries($recherche = null, $categorie = null, $langue = null, $admin = false, $limit = null)
    {
        $qb = $this->createQueryBuilder('g');

        /**
         * recherche via le titre
         */
        if(!empty($recherche)){
            $qb->andWhere('g.titre LIKE :recherche')
               ->setParameter('recherche', '%'.$recherche.'%');
        }

        /**
         * recherche via la catégorie
         */
        if(!empty($categorie)){
            $qb->andWhere('g.categorie = :categorie')
               ->setParameter('categorie', $categorie);
        }

        /**
         * recherche via la langue
         */
        if(!empty($langue)){
            $qb->andWhere('g.langue = :langue')
               ->setParameter('langue', $langue);
        }

        if($admin) $qb->orderBy('g.id', 'DESC');
        else{
            $qb->andWhere('g.isActive =  :isActive')
               ->setParameter('isActive', true)
               ->orderBy('g.poid', 'DESC');
        }

        if(!empty($limit)){
            $qb->setMaxResults($limit);
        }

        return $query = $qb->getQuery()->getResult();
    }

    public function getCurrentGalerie($id)
    {
        $qb = $this->createQueryBuilder('g')
            ->leftjoin('g.images', 'i', Expr\Join::WITH, 'i.isActive = :isActive')
            ->select('g, i')
            ->andWhere('g.isActive =  :isActive')
            ->andWhere('g.id = :id')
            ->setParameter('isActive', true)
            ->setParameter('id', $id)
            ->addOrderBy('i.poid', 'DESC');

        return $query = $qb->getQuery()->getOneOrNullResult();

    }
}
