admin_galerieimage_manager:
    path:     /admin/galerie-image/gestion
    defaults: { _controller: GalerieImageBundle:Galerie:managerAdmin }

admin_galerieimage_ajouter:
    path:     /admin/galerie-image/ajouter
    defaults: { _controller: GalerieImageBundle:Galerie:ajouterAdmin }

admin_galerieimage_publier:
    path:     /admin/galerie-image/publier/{id}
    defaults: { _controller: GalerieImageBundle:Galerie:publierAdmin }
    requirements:
        id: \d+

admin_galerieimage_poid:
    path:     /admin/galerie-image/poid/{id}/{poid}
    defaults:
        _controller: GalerieImageBundle:Galerie:poidAdmin
        poid : 1
    requirements:
        id: \d+
        poid: \d+

admin_galerieimage_modifier:
    path:     /admin/galerie-image/modifier/{id}
    defaults: { _controller: GalerieImageBundle:Galerie:modifierAdmin }
    requirements:
        id: \d+

admin_galerieimage_supprimer:
    path:     /admin/galerie-image/supprimer/{id}
    defaults: { _controller: GalerieImageBundle:Galerie:supprimerAdmin }
    requirements:
        id: \d+

admin_galerieimage_supprimer_image:
    path:     /admin/galerie-image/supprimer-image/{id}
    defaults: { _controller: GalerieImageBundle:Galerie:AdminSupprimerImage }
    requirements:
        id: \d+

client_galerieimage_manager:
    path:     /galeries-images
    defaults: { _controller: GalerieImageBundle:Galerie:managerClient }

client_galerieimage_view:
    path:     /galerie-image/{slug}/{id}
    defaults: { _controller: GalerieImageBundle:Galerie:viewClient }
    requirements:
        slug: ([a-z-0-9]*)
        id: \d+

#Catégorie
admin_galerieimage_categorie_manager:
    path:     /admin/galerie-image-categorie/manager
    defaults: { _controller: GalerieImageBundle:Categorie:managerAdmin }

admin_galerieimage_categorie_ajouter:
    path:     /admin/galerie-image-categorie/ajouter
    defaults: { _controller: GalerieImageBundle:Categorie:ajouterAdmin }

admin_galerieimage_categorie_modifier:
    path:     /admin/galerie-image-categorie/modifier/{id}
    defaults: { _controller: GalerieImageBundle:Categorie:modifierAdmin }
    requirements:
        id: \d+

admin_galerieimage_categorie_supprimer:
    path:     /admin/galerie-image-categorie/supprimer/{id}
    defaults: { _controller: GalerieImageBundle:Categorie:supprimerAdmin }
    requirements:
        id: \d+

#Image
admin_galerieimage_image_manager:
    path:     /admin/galerie-image-image/manager/{galerie}
    defaults: { _controller: GalerieImageBundle:Image:managerAdmin }
    requirements:
        galerie: \d+

admin_galerieimage_image_ajouter:
    path:     /admin/galerie-image-image/ajouter/{galerie}
    defaults: { _controller: GalerieImageBundle:Image:ajouterAdmin }
    requirements:
        galerie: \d+

admin_galerieimage_image_publier:
    path:     /admin/galerie-image-image/publier/{galerie}/{id}
    defaults: { _controller: GalerieImageBundle:Image:publierAdmin }
    requirements:
        galerie: \d+
        id: \d+

admin_galerieimage_image_modifier:
    path:     /admin/galerie-image-image/modifier/{galerie}/{id}
    defaults: { _controller: GalerieImageBundle:Image:modifierAdmin }
    requirements:
        galerie: \d+
        id: \d+

admin_galerieimage_image_supprimer:
    path:     /admingalerie-image-image/supprimer/{galerie}/{id}
    defaults: { _controller: GalerieImageBundle:Image:supprimerAdmin }
    requirements:
        galerie: \d+
        id: \d+

admin_galerieimage_image_poid:
    path:     /admingalerie-image-image/poid/{galerie}/{id}/{poid}
    defaults:
        _controller: GalerieImageBundle:Image:poidAdmin
        poid : 1
    requirements:
        galerie: \d+
        id: \d+
        poid: \d+

